#!/usr/bin/env tsx
/**
 * Export existing git-backed reado-station data as idempotent SQLite/D1 SQL.
 *
 * This is intentionally an export step, not a production cutover. The current
 * Astro + JSON path remains the source of truth until dual-write is verified.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'

import type { DigestData, SiteItem } from '../packages/shared/src/index.ts'
import type { CollectedData } from './lib/utils.js'
import {
  collectionRunStatement,
  digestStatement,
  insertOrReplace,
  opsStateStatements,
  siteItemStatement,
  sourceStatement,
  stableJson,
  type CollectionRunRow,
  type SourceConfig,
} from './lib/d1-sql.js'
import { getProjectRoot, readJSON } from './lib/utils.js'

interface ExportOptions {
  projectRoot: string
  outPath?: string
  stdout?: boolean
}

interface ExportStats {
  items: number
  digests: number
  sources: number
  collectionRuns: number
  opsStateKeys: number
}

function readRequiredJson<T>(path: string): T {
  const data = readJSON<T>(path)
  if (!data) throw new Error(`Failed to read JSON: ${path}`)
  return data
}

function readSiteItems(projectRoot: string): SiteItem[] {
  return readRequiredJson<SiteItem[]>(join(projectRoot, 'site', 'src', 'data', 'items.json'))
}

function readSiteDigests(projectRoot: string): DigestData[] {
  return readRequiredJson<DigestData[]>(join(projectRoot, 'site', 'src', 'data', 'digests.json'))
}

function readSources(projectRoot: string): SourceConfig[] {
  const payload = readRequiredJson<{ sources?: SourceConfig[] } | SourceConfig[]>(join(projectRoot, 'config', 'sources.json'))
  return Array.isArray(payload) ? payload : payload.sources ?? []
}

function readOpsState(projectRoot: string): Record<string, unknown> | null {
  const path = join(projectRoot, 'data', 'ops-state.json')
  if (!existsSync(path)) return null
  return readJSON<Record<string, unknown>>(path)
}

function inferMode(raw: CollectedData): string {
  const totalSources = raw.stats?.totalSources ?? 0
  const hasSuccessIds = (raw.stats?.successSourceIds?.length ?? 0) > 0
  return totalSources > 0 || hasSuccessIds ? 'backfill' : 'unknown'
}

function readCollectionRuns(projectRoot: string): CollectionRunRow[] {
  const dataRoot = join(projectRoot, 'data')
  if (!existsSync(dataRoot)) return []

  const runs: CollectionRunRow[] = []
  const years = readdirSync(dataRoot).filter((entry) => /^\d{4}$/.test(entry)).sort()

  for (const year of years) {
    const yearDir = join(dataRoot, year)
    const months = readdirSync(yearDir).filter((entry) => /^\d{2}$/.test(entry)).sort()
    for (const month of months) {
      const monthDir = join(yearDir, month)
      const days = readdirSync(monthDir).filter((entry) => /^\d{2}$/.test(entry)).sort()
      for (const day of days) {
        const date = `${year}-${month}-${day}`
        const dayDir = join(monthDir, day)
        const batches = readdirSync(dayDir).filter((entry) => existsSync(join(dayDir, entry, 'raw.json'))).sort()
        for (const batch of batches) {
          const raw = readJSON<CollectedData>(join(dayDir, batch, 'raw.json'))
          if (!raw) continue
          runs.push({
            date,
            batch,
            mode: inferMode(raw),
            fetchedAt: raw.fetchedAt ?? null,
            totalSources: raw.stats?.totalSources ?? null,
            successSources: raw.stats?.successSources ?? null,
            failedSources: raw.stats?.failedSources ?? null,
            totalItems: raw.stats?.totalItems ?? raw.items?.length ?? null,
            deduplicated: raw.stats?.deduplicatedItems ?? null,
            failedSourceIds: raw.stats?.failedSourceIds ?? [],
            successSourceIds: raw.stats?.successSourceIds ?? [],
          })
        }
      }
    }
  }

  return runs
}

export function buildBackfillSql(options: ExportOptions): { sql: string; stats: ExportStats } {
  const items = readSiteItems(options.projectRoot)
  const digests = readSiteDigests(options.projectRoot)
  const sources = readSources(options.projectRoot)
  const collectionRuns = readCollectionRuns(options.projectRoot)
  const opsState = readOpsState(options.projectRoot)
  const opsStatements = opsStateStatements(opsState)

  const lines = [
    '-- Generated by scripts/export-d1-backfill.ts',
    `-- Generated at ${new Date().toISOString()}`,
    'PRAGMA foreign_keys = OFF;',
    'BEGIN TRANSACTION;',
    ...sources.map((source) => sourceStatement(source)),
    ...items.map((item) => siteItemStatement(item)),
    ...digests.map((digest) => digestStatement(digest)),
    ...collectionRuns.map(collectionRunStatement),
    ...opsStatements,
    'COMMIT;',
    'PRAGMA foreign_keys = ON;',
    '',
  ]

  return {
    sql: lines.join('\n'),
    stats: {
      items: items.length,
      digests: digests.length,
      sources: sources.length,
      collectionRuns: collectionRuns.length,
      opsStateKeys: opsStatements.length,
    },
  }
}

function parseArgs(args: string[]): { outPath: string | undefined; stdout: boolean } {
  let outPath: string | undefined = join(getProjectRoot(), 'dist', 'd1', 'backfill.sql')
  let stdout = false

  for (let i = 0; i < args.length; i++) {
    const arg = args[i]
    if (arg === '--stdout') {
      stdout = true
      outPath = undefined
    } else if (arg === '--out') {
      outPath = args[++i]
      if (!outPath) throw new Error('--out requires a path')
    } else if (arg === '--help' || arg === '-h') {
      console.log('Usage: npm run d1:backfill -- [--out dist/d1/backfill.sql | --stdout]')
      process.exit(0)
    } else {
      throw new Error(`Unknown argument: ${arg}`)
    }
  }

  return { outPath, stdout }
}

async function main() {
  const { outPath, stdout } = parseArgs(process.argv.slice(2))
  const { sql, stats } = buildBackfillSql({ projectRoot: getProjectRoot(), outPath, stdout })

  if (stdout) {
    process.stdout.write(sql)
    return
  }

  if (!outPath) throw new Error('No output path provided')
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, sql, 'utf8')

  console.log(JSON.stringify({ status: 'ok', outPath, stats }, null, 2))
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
